#!/usr/bin/env python

"""
Parses 23andMe genome into variable `genome` and starts a Python REPL.

Use this for quickly querying a genome by hand.

Exmaple:

    $ repl genome.txt
    Type `genome` to see Genome parsed from genome.txt
    >>> genome
    <Genome: SNPs=949461, ychromo=True, orientation=1>
    >>> genome.rs123
    SNP(genotype=[Nucleotide('A'), Nucleotide('A')], rsid='rs123',
            orientation=1)
"""

import code
import sys

def repl(file):
    env = dict(globals())
    exec("from dna_traits import *\ngenome = parse('%s')" % file, env, env)
    code.interact("Type `genome` to see Genome parsed from %s" % file,
            local=env)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: repl genome.txt")
        print("Starts a Python REPL with the variable `genome` initialized")
        print("from the 23andMe genome data in the file.")
        sys.exit(1)

    repl(sys.argv[1])
